"""add_ai_pending_to_dip_ai_analysis

Revision ID: 17324cd39318
Revises: 74c5e4daa063
Create Date: 2025-12-29 16:48:11.202241+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17324cd39318"
down_revision: Union[str, None] = "74c5e4daa063"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Add column with server_default=False for existing rows
    op.add_column(
        "dip_ai_analysis",
        sa.Column("ai_pending", sa.Boolean(), nullable=False, server_default=sa.text("FALSE"))
    )
    # Remove server_default after migration (optional, keeps clean)
    op.alter_column("dip_ai_analysis", "ai_pending", server_default=None)


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dip_ai_analysis", "ai_pending")
    # ### end Alembic commands ###
