"""add_opportunity_type_to_dip_state

Revision ID: 322fb07d2183
Revises: ec98cb56b782
Create Date: 2025-12-29 13:30:35.858905+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "322fb07d2183"
down_revision: Union[str, None] = "ec98cb56b782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dip_state", sa.Column("opportunity_type", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dip_state", "opportunity_type")
    # ### end Alembic commands ###
