"""add_portfolio_ai_analysis_fields

Revision ID: 8628a993c359
Revises: 425459551ea8
Create Date: 2025-12-30 10:56:36.557797+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8628a993c359"
down_revision: Union[str, None] = "425459551ea8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolios", sa.Column("ai_analysis_summary", sa.Text(), nullable=True))
    op.add_column("portfolios", sa.Column("ai_analysis_hash", sa.String(length=32), nullable=True))
    op.add_column(
        "portfolios", sa.Column("ai_analysis_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolios", "ai_analysis_at")
    op.drop_column("portfolios", "ai_analysis_hash")
    op.drop_column("portfolios", "ai_analysis_summary")
    # ### end Alembic commands ###
