"""initial_schema

Revision ID: de8f24192475
Revises:
Create Date: 2025-12-26 11:14:06.586603+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "de8f24192475"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_agent_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("verdicts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overall_signal", sa.String(length=20), nullable=False),
        sa.Column("overall_confidence", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "analyzed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "overall_signal IN ('bullish', 'bearish', 'neutral')",
            name=op.f("ck_ai_agent_analysis_ck_ai_overall_signal"),
        ),
        sa.CheckConstraint(
            "overall_confidence >= 0 AND overall_confidence <= 100",
            name=op.f("ck_ai_agent_analysis_ck_ai_confidence_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_agent_analysis")),
        sa.UniqueConstraint("symbol", name=op.f("uq_ai_agent_analysis_symbol")),
    )
    op.create_index(
        "idx_ai_agent_analysis_expires", "ai_agent_analysis", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_ai_agent_analysis_signal", "ai_agent_analysis", ["overall_signal"], unique=False
    )
    op.create_index("idx_ai_agent_analysis_symbol", "ai_agent_analysis", ["symbol"], unique=False)
    op.create_table(
        "analysis_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("analysis_type", sa.String(length=50), nullable=False),
        sa.Column("input_version_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("batch_job_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_versions")),
        sa.UniqueConstraint("symbol", "analysis_type", name="uq_analysis_version_symbol_type"),
    )
    op.create_index(
        "idx_analysis_versions_expires", "analysis_versions", ["expires_at"], unique=False
    )
    op.create_index("idx_analysis_versions_symbol", "analysis_versions", ["symbol"], unique=False)
    op.create_index(
        "idx_analysis_versions_type", "analysis_versions", ["analysis_type"], unique=False
    )
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("endpoint", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("is_batch", sa.Boolean(), nullable=False),
        sa.Column("request_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_usage")),
    )
    op.create_index(
        "idx_api_usage_recorded",
        "api_usage",
        ["recorded_at"],
        unique=False,
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.create_index("idx_api_usage_service", "api_usage", ["service"], unique=False)
    op.create_table(
        "auth_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=64), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_backup_codes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_user")),
        sa.UniqueConstraint("username", name=op.f("uq_auth_user_username")),
    )
    op.create_index("idx_auth_user_username", "auth_user", ["username"], unique=False)
    op.create_table(
        "batch_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=100), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("completed_requests", sa.Integer(), nullable=False),
        sa.Column("failed_requests", sa.Integer(), nullable=False),
        sa.Column("input_file_id", sa.String(length=100), nullable=True),
        sa.Column("output_file_id", sa.String(length=100), nullable=True),
        sa.Column("error_file_id", sa.String(length=100), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("actual_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("task_custom_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'validating', 'in_progress', 'finalizing', 'completed', 'failed', 'expired', 'cancelled')",
            name=op.f("ck_batch_jobs_ck_batch_job_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_jobs")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_batch_jobs_batch_id")),
    )
    op.create_index(
        "idx_batch_jobs_created",
        "batch_jobs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index("idx_batch_jobs_status", "batch_jobs", ["status"], unique=False)
    op.create_index("idx_batch_jobs_type", "batch_jobs", ["job_type"], unique=False)
    op.create_table(
        "cronjobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cron", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=20), nullable=True),
        sa.Column("last_duration_ms", sa.Integer(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cronjobs")),
        sa.UniqueConstraint("name", name=op.f("uq_cronjobs_name")),
    )
    op.create_index(
        "idx_cronjobs_active",
        "cronjobs",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = TRUE"),
    )
    op.create_index("idx_cronjobs_next_run", "cronjobs", ["next_run"], unique=False)
    op.create_table(
        "data_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("version_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('prices', 'fundamentals', 'calendar')",
            name=op.f("ck_data_versions_ck_data_version_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_versions")),
        sa.UniqueConstraint("symbol", "source", name="uq_data_version_symbol_source"),
    )
    op.create_index("idx_data_versions_source", "data_versions", ["source"], unique=False)
    op.create_index("idx_data_versions_symbol", "data_versions", ["symbol"], unique=False)
    op.create_index(
        "idx_data_versions_updated",
        "data_versions",
        ["updated_at"],
        unique=False,
        postgresql_ops={"updated_at": "DESC"},
    )
    op.create_table(
        "dip_ai_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("swipe_bio", sa.Text(), nullable=True),
        sa.Column("ai_rating", sa.String(length=20), nullable=True),
        sa.Column("rating_reasoning", sa.Text(), nullable=True),
        sa.Column("model_used", sa.String(length=50), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("is_batch_generated", sa.Boolean(), nullable=False),
        sa.Column("batch_job_id", sa.String(length=100), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ai_rating IS NULL OR ai_rating IN ('strong_buy', 'buy', 'hold', 'sell', 'strong_sell')",
            name=op.f("ck_dip_ai_analysis_ck_ai_rating"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dip_ai_analysis")),
        sa.UniqueConstraint("symbol", name=op.f("uq_dip_ai_analysis_symbol")),
    )
    op.create_index("idx_dip_ai_analysis_expires", "dip_ai_analysis", ["expires_at"], unique=False)
    op.create_index("idx_dip_ai_analysis_rating", "dip_ai_analysis", ["ai_rating"], unique=False)
    op.create_index("idx_dip_ai_analysis_symbol", "dip_ai_analysis", ["symbol"], unique=False)
    op.create_table(
        "dip_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ath_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("dip_percentage", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('added', 'removed', 'updated')",
            name=op.f("ck_dip_history_ck_dip_history_action"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dip_history")),
    )
    op.create_index("idx_dip_history_action", "dip_history", ["action"], unique=False)
    op.create_index(
        "idx_dip_history_recorded",
        "dip_history",
        ["recorded_at"],
        unique=False,
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.create_index("idx_dip_history_symbol", "dip_history", ["symbol"], unique=False)
    op.create_table(
        "dipfinder_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("dip_pct", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("final_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("dip_class", sa.String(length=20), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('entered_dip', 'exited_dip', 'deepened', 'recovered', 'alert_triggered')",
            name=op.f("ck_dipfinder_history_ck_dipfinder_history_event"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dipfinder_history")),
    )
    op.create_index(
        "idx_dipfinder_history_event", "dipfinder_history", ["event_type"], unique=False
    )
    op.create_index(
        "idx_dipfinder_history_recorded",
        "dipfinder_history",
        ["recorded_at"],
        unique=False,
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.create_index("idx_dipfinder_history_ticker", "dipfinder_history", ["ticker"], unique=False)
    op.create_table(
        "dipfinder_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("benchmark", sa.String(length=20), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("dip_stock", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("peak_stock", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("dip_pctl", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("dip_vs_typical", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("persist_days", sa.Integer(), nullable=True),
        sa.Column("dip_mkt", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("excess_dip", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("dip_class", sa.String(length=20), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("stability_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("dip_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("final_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("alert_level", sa.String(length=20), nullable=True),
        sa.Column("should_alert", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("quality_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stability_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dipfinder_signals")),
        sa.UniqueConstraint(
            "ticker", "benchmark", "window_days", "as_of_date", name="uq_dipfinder_signal"
        ),
    )
    op.create_index(
        "idx_dipfinder_signals_alert",
        "dipfinder_signals",
        ["should_alert"],
        unique=False,
        postgresql_where=sa.text("should_alert = TRUE"),
    )
    op.create_index(
        "idx_dipfinder_signals_date",
        "dipfinder_signals",
        ["as_of_date"],
        unique=False,
        postgresql_ops={"as_of_date": "DESC"},
    )
    op.create_index(
        "idx_dipfinder_signals_expires", "dipfinder_signals", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_dipfinder_signals_final",
        "dipfinder_signals",
        ["final_score"],
        unique=False,
        postgresql_ops={"final_score": "DESC"},
    )
    op.create_index(
        "idx_dipfinder_signals_lookup",
        "dipfinder_signals",
        ["ticker", "benchmark", "window_days", "as_of_date"],
        unique=False,
    )
    op.create_index("idx_dipfinder_signals_ticker", "dipfinder_signals", ["ticker"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=16, scale=6), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
        sa.UniqueConstraint("symbol", "date", name="uq_price_history"),
    )
    op.create_index(
        "idx_price_history_date",
        "price_history",
        ["date"],
        unique=False,
        postgresql_ops={"date": "DESC"},
    )
    op.create_index("idx_price_history_symbol", "price_history", ["symbol"], unique=False)
    op.create_index(
        "idx_price_history_symbol_date", "price_history", ["symbol", "date"], unique=False
    )
    op.create_table(
        "rate_limit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=100), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column(
            "window_start",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_request_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_log")),
    )
    op.create_index(
        "idx_rate_limit_identifier", "rate_limit_log", ["identifier", "endpoint"], unique=False
    )
    op.create_index("idx_rate_limit_window", "rate_limit_log", ["window_start"], unique=False)
    op.create_table(
        "runtime_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_runtime_settings")),
    )
    op.create_table(
        "schema_migrations",
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_schema_migrations")),
    )
    op.create_table(
        "stock_fundamentals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("pe_ratio", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("forward_pe", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("peg_ratio", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("price_to_book", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("price_to_sales", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("enterprise_value", sa.BigInteger(), nullable=True),
        sa.Column("ev_to_ebitda", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ev_to_revenue", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("profit_margin", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("operating_margin", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("gross_margin", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("ebitda_margin", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("return_on_equity", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("return_on_assets", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("debt_to_equity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("current_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("quick_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("total_cash", sa.BigInteger(), nullable=True),
        sa.Column("total_debt", sa.BigInteger(), nullable=True),
        sa.Column("free_cash_flow", sa.BigInteger(), nullable=True),
        sa.Column("operating_cash_flow", sa.BigInteger(), nullable=True),
        sa.Column("book_value", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("eps_trailing", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("eps_forward", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("revenue_per_share", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("revenue_growth", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("earnings_growth", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("earnings_quarterly_growth", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("shares_outstanding", sa.BigInteger(), nullable=True),
        sa.Column("float_shares", sa.BigInteger(), nullable=True),
        sa.Column("held_percent_insiders", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("held_percent_institutions", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("short_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("short_percent_of_float", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("beta", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("recommendation", sa.String(length=20), nullable=True),
        sa.Column("recommendation_mean", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("num_analyst_opinions", sa.Integer(), nullable=True),
        sa.Column("target_high_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("target_low_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("target_mean_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("target_median_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("revenue", sa.BigInteger(), nullable=True),
        sa.Column("ebitda", sa.BigInteger(), nullable=True),
        sa.Column("net_income", sa.BigInteger(), nullable=True),
        sa.Column("next_earnings_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("earnings_estimate_high", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("earnings_estimate_low", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("earnings_estimate_avg", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("earnings_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("domain", sa.String(length=20), nullable=True),
        sa.Column("income_stmt_quarterly", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("income_stmt_annual", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "balance_sheet_quarterly", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("balance_sheet_annual", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cash_flow_quarterly", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cash_flow_annual", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("net_interest_income", sa.BigInteger(), nullable=True),
        sa.Column("net_interest_margin", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("ffo", sa.BigInteger(), nullable=True),
        sa.Column("ffo_per_share", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("p_ffo", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("loss_ratio", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("combined_ratio", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("financials_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_fundamentals")),
        sa.UniqueConstraint("symbol", name=op.f("uq_stock_fundamentals_symbol")),
    )
    op.create_index("idx_stock_fundamentals_domain", "stock_fundamentals", ["domain"], unique=False)
    op.create_index(
        "idx_stock_fundamentals_expires", "stock_fundamentals", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_stock_fundamentals_next_earnings",
        "stock_fundamentals",
        ["next_earnings_date"],
        unique=False,
    )
    op.create_index("idx_stock_fundamentals_symbol", "stock_fundamentals", ["symbol"], unique=False)
    op.create_table(
        "symbol_ingest_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed')",
            name=op.f("ck_symbol_ingest_queue_ck_ingest_queue_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbol_ingest_queue")),
        sa.UniqueConstraint("symbol", name=op.f("uq_symbol_ingest_queue_symbol")),
    )
    op.create_index(
        "idx_ingest_queue_pending",
        "symbol_ingest_queue",
        ["status", "queued_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("idx_ingest_queue_status", "symbol_ingest_queue", ["status"], unique=False)
    op.create_table(
        "symbol_search_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(length=100), nullable=False),
        sa.Column("query_normalized", sa.String(length=100), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("user_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('local', 'api', 'mixed')",
            name=op.f("ck_symbol_search_log_ck_search_log_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbol_search_log")),
    )
    op.create_index("idx_search_log_query", "symbol_search_log", ["query_normalized"], unique=False)
    op.create_index(
        "idx_search_log_searched",
        "symbol_search_log",
        ["searched_at"],
        unique=False,
        postgresql_ops={"searched_at": "DESC"},
    )
    op.create_table(
        "symbol_search_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("exchange", sa.String(length=50), nullable=True),
        sa.Column("quote_type", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("search_query", sa.String(length=100), nullable=True),
        sa.Column("relevance_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "confidence_score",
            sa.Numeric(precision=4, scale=3),
            nullable=True,
            comment="Combined score (0-1) from relevance, recency, and data quality",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last time this result was returned in a search",
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbol_search_results")),
        sa.UniqueConstraint("symbol", name="uq_symbol_search_result"),
    )
    op.create_index(
        "idx_search_results_expires", "symbol_search_results", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_search_results_query", "symbol_search_results", ["search_query"], unique=False
    )
    op.create_index("idx_search_results_symbol", "symbol_search_results", ["symbol"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("summary_ai", sa.String(length=500), nullable=True),
        sa.Column("symbol_type", sa.String(length=20), nullable=False),
        sa.Column("min_dip_pct", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("min_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("logo_light", sa.LargeBinary(), nullable=True),
        sa.Column("logo_dark", sa.LargeBinary(), nullable=True),
        sa.Column("logo_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logo_source", sa.String(length=50), nullable=True),
        sa.Column("fetch_status", sa.String(length=20), nullable=False),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbols")),
        sa.UniqueConstraint("symbol", name=op.f("uq_symbols_symbol")),
    )
    op.create_index("idx_symbols_logo_fetched_at", "symbols", ["logo_fetched_at"], unique=False)
    op.create_index("idx_symbols_sector", "symbols", ["sector"], unique=False)
    op.create_index("idx_symbols_symbol", "symbols", ["symbol"], unique=False)
    op.create_index("idx_symbols_type", "symbols", ["symbol_type"], unique=False)
    op.create_table(
        "yfinance_info_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_yfinance_info_cache")),
        sa.UniqueConstraint("symbol", name=op.f("uq_yfinance_info_cache_symbol")),
    )
    op.create_index(
        "idx_yfinance_cache_expires", "yfinance_info_cache", ["expires_at"], unique=False
    )
    op.create_index("idx_yfinance_cache_symbol", "yfinance_info_cache", ["symbol"], unique=False)
    op.create_table(
        "batch_task_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=100), nullable=False),
        sa.Column("custom_id", sa.String(length=200), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("agent_id", sa.String(length=50), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("original_request", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'retrying', 'resolved', 'abandoned')",
            name=op.f("ck_batch_task_errors_ck_batch_task_errors_status"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch_jobs.batch_id"],
            name=op.f("fk_batch_task_errors_batch_id_batch_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_task_errors")),
    )
    op.create_index("idx_batch_task_errors_batch", "batch_task_errors", ["batch_id"], unique=False)
    op.create_index(
        "idx_batch_task_errors_pending",
        "batch_task_errors",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("idx_batch_task_errors_status", "batch_task_errors", ["status"], unique=False)
    op.create_index("idx_batch_task_errors_symbol", "batch_task_errors", ["symbol"], unique=False)
    op.create_table(
        "dip_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ath_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("dip_percentage", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("dip_start_date", sa.Date(), nullable=True),
        sa.Column("ref_high", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("last_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("days_below", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["symbols.symbol"],
            name=op.f("fk_dip_state_symbol_symbols"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dip_state")),
        sa.UniqueConstraint("symbol", name=op.f("uq_dip_state_symbol")),
    )
    op.create_index(
        "idx_dip_state_percentage",
        "dip_state",
        ["dip_percentage"],
        unique=False,
        postgresql_ops={"dip_percentage": "DESC"},
    )
    op.create_index("idx_dip_state_start_date", "dip_state", ["dip_start_date"], unique=False)
    op.create_index("idx_dip_state_symbol", "dip_state", ["symbol"], unique=False)
    op.create_index(
        "idx_dip_state_updated",
        "dip_state",
        ["last_updated"],
        unique=False,
        postgresql_ops={"last_updated": "DESC"},
    )
    op.create_table(
        "dipfinder_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("min_dip_abs", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("min_persist_days", sa.Integer(), nullable=False),
        sa.Column("dip_percentile_threshold", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("dip_vs_typical_threshold", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("quality_gate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("stability_gate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["symbols.symbol"],
            name=op.f("fk_dipfinder_config_symbol_symbols"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dipfinder_config")),
        sa.UniqueConstraint("symbol", name=op.f("uq_dipfinder_config_symbol")),
    )
    op.create_index(
        "idx_dipfinder_config_enabled",
        "dipfinder_config",
        ["is_enabled"],
        unique=False,
        postgresql_where=sa.text("is_enabled = TRUE"),
    )
    op.create_index("idx_dipfinder_config_symbol", "dipfinder_config", ["symbol"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_currency", sa.String(length=10), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("fk_portfolios_user_id_auth_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
    )
    op.create_index(
        "idx_portfolios_active",
        "portfolios",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = TRUE"),
    )
    op.create_index("idx_portfolios_user", "portfolios", ["user_id"], unique=False)
    op.create_table(
        "secure_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("encrypted_key", sa.Text(), nullable=False),
        sa.Column("key_hint", sa.String(length=20), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["auth_user.id"], name=op.f("fk_secure_api_keys_created_by_auth_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secure_api_keys")),
        sa.UniqueConstraint("service_name", name=op.f("uq_secure_api_keys_service_name")),
    )
    op.create_index(
        "idx_secure_api_keys_service", "secure_api_keys", ["service_name"], unique=False
    )
    op.create_table(
        "stock_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("ipo_year", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("vote_score", sa.Integer(), nullable=False),
        sa.Column("fetch_status", sa.String(length=20), nullable=False),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ath_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_stock_suggestions_ck_suggestion_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["auth_user.id"],
            name=op.f("fk_stock_suggestions_approved_by_auth_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_suggestions")),
        sa.UniqueConstraint("symbol", name=op.f("uq_stock_suggestions_symbol")),
    )
    op.create_index(
        "idx_suggestions_score",
        "stock_suggestions",
        ["vote_score"],
        unique=False,
        postgresql_ops={"vote_score": "DESC"},
    )
    op.create_index("idx_suggestions_status", "stock_suggestions", ["status"], unique=False)
    op.create_index("idx_suggestions_symbol", "stock_suggestions", ["symbol"], unique=False)
    op.create_table(
        "user_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("vote_weight", sa.Integer(), nullable=False),
        sa.Column("rate_limit_bypass", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth_user.id"], name=op.f("fk_user_api_keys_user_id_auth_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_user_api_keys_key_hash")),
    )
    op.create_index(
        "idx_user_api_keys_active",
        "user_api_keys",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = TRUE"),
    )
    op.create_index("idx_user_api_keys_hash", "user_api_keys", ["key_hash"], unique=False)
    op.create_table(
        "dip_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("vote_type", sa.String(length=10), nullable=False),
        sa.Column("vote_weight", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "vote_type IN ('buy', 'sell')", name=op.f("ck_dip_votes_ck_dip_vote_type")
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["user_api_keys.id"], name=op.f("fk_dip_votes_api_key_id_user_api_keys")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dip_votes")),
        sa.UniqueConstraint("symbol", "fingerprint", name="uq_dip_vote"),
    )
    op.create_index(
        "idx_dip_votes_created",
        "dip_votes",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index("idx_dip_votes_fingerprint", "dip_votes", ["fingerprint"], unique=False)
    op.create_index("idx_dip_votes_symbol", "dip_votes", ["symbol"], unique=False)
    op.create_table(
        "portfolio_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(length=50), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("window", sa.String(length=50), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'error', 'partial')",
            name=op.f("ck_portfolio_analytics_ck_portfolio_analytics_status"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_analytics_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_analytics")),
    )
    op.create_index(
        "idx_portfolio_analytics_created",
        "portfolio_analytics",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_portfolio_analytics_portfolio", "portfolio_analytics", ["portfolio_id"], unique=False
    )
    op.create_index("idx_portfolio_analytics_tool", "portfolio_analytics", ["tool"], unique=False)
    op.create_table(
        "portfolio_analytics_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("window", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("benchmark", sa.String(length=20), nullable=True),
        sa.Column("force_refresh", sa.Boolean(), nullable=False),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_portfolio_analytics_jobs_ck_portfolio_analytics_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_analytics_jobs_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("fk_portfolio_analytics_jobs_user_id_auth_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_analytics_jobs")),
        sa.UniqueConstraint("job_id", name=op.f("uq_portfolio_analytics_jobs_job_id")),
    )
    op.create_index(
        "idx_portfolio_analytics_jobs_created",
        "portfolio_analytics_jobs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_portfolio_analytics_jobs_portfolio",
        "portfolio_analytics_jobs",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        "idx_portfolio_analytics_jobs_status", "portfolio_analytics_jobs", ["status"], unique=False
    )
    op.create_index(
        "idx_portfolio_analytics_jobs_user", "portfolio_analytics_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "portfolio_holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target_weight", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_holdings_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_holdings")),
        sa.UniqueConstraint("portfolio_id", "symbol", name="uq_portfolio_holdings_symbol"),
    )
    op.create_index(
        "idx_portfolio_holdings_portfolio", "portfolio_holdings", ["portfolio_id"], unique=False
    )
    op.create_index("idx_portfolio_holdings_symbol", "portfolio_holdings", ["symbol"], unique=False)
    op.create_table(
        "portfolio_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("fees", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "side IN ('buy', 'sell', 'dividend', 'split', 'deposit', 'withdrawal')",
            name=op.f("ck_portfolio_transactions_ck_portfolio_transactions_side"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_transactions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_transactions")),
    )
    op.create_index(
        "idx_portfolio_transactions_date",
        "portfolio_transactions",
        ["trade_date"],
        unique=False,
        postgresql_ops={"trade_date": "DESC"},
    )
    op.create_index(
        "idx_portfolio_transactions_portfolio",
        "portfolio_transactions",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        "idx_portfolio_transactions_symbol", "portfolio_transactions", ["symbol"], unique=False
    )
    op.create_table(
        "suggestion_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("suggestion_id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("vote_type", sa.String(length=10), nullable=False),
        sa.Column("vote_weight", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "vote_type IN ('up', 'down')", name=op.f("ck_suggestion_votes_ck_suggestion_vote_type")
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["user_api_keys.id"],
            name=op.f("fk_suggestion_votes_api_key_id_user_api_keys"),
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["stock_suggestions.id"],
            name=op.f("fk_suggestion_votes_suggestion_id_stock_suggestions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggestion_votes")),
        sa.UniqueConstraint("suggestion_id", "fingerprint", name="uq_suggestion_vote"),
    )
    op.create_index(
        "idx_suggestion_votes_suggestion", "suggestion_votes", ["suggestion_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_suggestion_votes_suggestion", table_name="suggestion_votes")
    op.drop_table("suggestion_votes")
    op.drop_index("idx_portfolio_transactions_symbol", table_name="portfolio_transactions")
    op.drop_index("idx_portfolio_transactions_portfolio", table_name="portfolio_transactions")
    op.drop_index(
        "idx_portfolio_transactions_date",
        table_name="portfolio_transactions",
        postgresql_ops={"trade_date": "DESC"},
    )
    op.drop_table("portfolio_transactions")
    op.drop_index("idx_portfolio_holdings_symbol", table_name="portfolio_holdings")
    op.drop_index("idx_portfolio_holdings_portfolio", table_name="portfolio_holdings")
    op.drop_table("portfolio_holdings")
    op.drop_index("idx_portfolio_analytics_jobs_user", table_name="portfolio_analytics_jobs")
    op.drop_index("idx_portfolio_analytics_jobs_status", table_name="portfolio_analytics_jobs")
    op.drop_index("idx_portfolio_analytics_jobs_portfolio", table_name="portfolio_analytics_jobs")
    op.drop_index(
        "idx_portfolio_analytics_jobs_created",
        table_name="portfolio_analytics_jobs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_table("portfolio_analytics_jobs")
    op.drop_index("idx_portfolio_analytics_tool", table_name="portfolio_analytics")
    op.drop_index("idx_portfolio_analytics_portfolio", table_name="portfolio_analytics")
    op.drop_index(
        "idx_portfolio_analytics_created",
        table_name="portfolio_analytics",
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_table("portfolio_analytics")
    op.drop_index("idx_dip_votes_symbol", table_name="dip_votes")
    op.drop_index("idx_dip_votes_fingerprint", table_name="dip_votes")
    op.drop_index(
        "idx_dip_votes_created", table_name="dip_votes", postgresql_ops={"created_at": "DESC"}
    )
    op.drop_table("dip_votes")
    op.drop_index("idx_user_api_keys_hash", table_name="user_api_keys")
    op.drop_index(
        "idx_user_api_keys_active",
        table_name="user_api_keys",
        postgresql_where=sa.text("is_active = TRUE"),
    )
    op.drop_table("user_api_keys")
    op.drop_index("idx_suggestions_symbol", table_name="stock_suggestions")
    op.drop_index("idx_suggestions_status", table_name="stock_suggestions")
    op.drop_index(
        "idx_suggestions_score",
        table_name="stock_suggestions",
        postgresql_ops={"vote_score": "DESC"},
    )
    op.drop_table("stock_suggestions")
    op.drop_index("idx_secure_api_keys_service", table_name="secure_api_keys")
    op.drop_table("secure_api_keys")
    op.drop_index("idx_portfolios_user", table_name="portfolios")
    op.drop_index(
        "idx_portfolios_active",
        table_name="portfolios",
        postgresql_where=sa.text("is_active = TRUE"),
    )
    op.drop_table("portfolios")
    op.drop_index("idx_dipfinder_config_symbol", table_name="dipfinder_config")
    op.drop_index(
        "idx_dipfinder_config_enabled",
        table_name="dipfinder_config",
        postgresql_where=sa.text("is_enabled = TRUE"),
    )
    op.drop_table("dipfinder_config")
    op.drop_index(
        "idx_dip_state_updated", table_name="dip_state", postgresql_ops={"last_updated": "DESC"}
    )
    op.drop_index("idx_dip_state_symbol", table_name="dip_state")
    op.drop_index("idx_dip_state_start_date", table_name="dip_state")
    op.drop_index(
        "idx_dip_state_percentage",
        table_name="dip_state",
        postgresql_ops={"dip_percentage": "DESC"},
    )
    op.drop_table("dip_state")
    op.drop_index("idx_batch_task_errors_symbol", table_name="batch_task_errors")
    op.drop_index("idx_batch_task_errors_status", table_name="batch_task_errors")
    op.drop_index(
        "idx_batch_task_errors_pending",
        table_name="batch_task_errors",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("idx_batch_task_errors_batch", table_name="batch_task_errors")
    op.drop_table("batch_task_errors")
    op.drop_index("idx_yfinance_cache_symbol", table_name="yfinance_info_cache")
    op.drop_index("idx_yfinance_cache_expires", table_name="yfinance_info_cache")
    op.drop_table("yfinance_info_cache")
    op.drop_index("idx_symbols_type", table_name="symbols")
    op.drop_index("idx_symbols_symbol", table_name="symbols")
    op.drop_index("idx_symbols_sector", table_name="symbols")
    op.drop_index("idx_symbols_logo_fetched_at", table_name="symbols")
    op.drop_table("symbols")
    op.drop_index("idx_search_results_symbol", table_name="symbol_search_results")
    op.drop_index("idx_search_results_query", table_name="symbol_search_results")
    op.drop_index("idx_search_results_expires", table_name="symbol_search_results")
    op.drop_table("symbol_search_results")
    op.drop_index(
        "idx_search_log_searched",
        table_name="symbol_search_log",
        postgresql_ops={"searched_at": "DESC"},
    )
    op.drop_index("idx_search_log_query", table_name="symbol_search_log")
    op.drop_table("symbol_search_log")
    op.drop_index("idx_ingest_queue_status", table_name="symbol_ingest_queue")
    op.drop_index(
        "idx_ingest_queue_pending",
        table_name="symbol_ingest_queue",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("symbol_ingest_queue")
    op.drop_index("idx_stock_fundamentals_symbol", table_name="stock_fundamentals")
    op.drop_index("idx_stock_fundamentals_next_earnings", table_name="stock_fundamentals")
    op.drop_index("idx_stock_fundamentals_expires", table_name="stock_fundamentals")
    op.drop_index("idx_stock_fundamentals_domain", table_name="stock_fundamentals")
    op.drop_table("stock_fundamentals")
    op.drop_table("schema_migrations")
    op.drop_table("runtime_settings")
    op.drop_index("idx_rate_limit_window", table_name="rate_limit_log")
    op.drop_index("idx_rate_limit_identifier", table_name="rate_limit_log")
    op.drop_table("rate_limit_log")
    op.drop_index("idx_price_history_symbol_date", table_name="price_history")
    op.drop_index("idx_price_history_symbol", table_name="price_history")
    op.drop_index(
        "idx_price_history_date", table_name="price_history", postgresql_ops={"date": "DESC"}
    )
    op.drop_table("price_history")
    op.drop_index("idx_dipfinder_signals_ticker", table_name="dipfinder_signals")
    op.drop_index("idx_dipfinder_signals_lookup", table_name="dipfinder_signals")
    op.drop_index(
        "idx_dipfinder_signals_final",
        table_name="dipfinder_signals",
        postgresql_ops={"final_score": "DESC"},
    )
    op.drop_index("idx_dipfinder_signals_expires", table_name="dipfinder_signals")
    op.drop_index(
        "idx_dipfinder_signals_date",
        table_name="dipfinder_signals",
        postgresql_ops={"as_of_date": "DESC"},
    )
    op.drop_index(
        "idx_dipfinder_signals_alert",
        table_name="dipfinder_signals",
        postgresql_where=sa.text("should_alert = TRUE"),
    )
    op.drop_table("dipfinder_signals")
    op.drop_index("idx_dipfinder_history_ticker", table_name="dipfinder_history")
    op.drop_index(
        "idx_dipfinder_history_recorded",
        table_name="dipfinder_history",
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.drop_index("idx_dipfinder_history_event", table_name="dipfinder_history")
    op.drop_table("dipfinder_history")
    op.drop_index("idx_dip_history_symbol", table_name="dip_history")
    op.drop_index(
        "idx_dip_history_recorded", table_name="dip_history", postgresql_ops={"recorded_at": "DESC"}
    )
    op.drop_index("idx_dip_history_action", table_name="dip_history")
    op.drop_table("dip_history")
    op.drop_index("idx_dip_ai_analysis_symbol", table_name="dip_ai_analysis")
    op.drop_index("idx_dip_ai_analysis_rating", table_name="dip_ai_analysis")
    op.drop_index("idx_dip_ai_analysis_expires", table_name="dip_ai_analysis")
    op.drop_table("dip_ai_analysis")
    op.drop_index(
        "idx_data_versions_updated",
        table_name="data_versions",
        postgresql_ops={"updated_at": "DESC"},
    )
    op.drop_index("idx_data_versions_symbol", table_name="data_versions")
    op.drop_index("idx_data_versions_source", table_name="data_versions")
    op.drop_table("data_versions")
    op.drop_index("idx_cronjobs_next_run", table_name="cronjobs")
    op.drop_index(
        "idx_cronjobs_active", table_name="cronjobs", postgresql_where=sa.text("is_active = TRUE")
    )
    op.drop_table("cronjobs")
    op.drop_index("idx_batch_jobs_type", table_name="batch_jobs")
    op.drop_index("idx_batch_jobs_status", table_name="batch_jobs")
    op.drop_index(
        "idx_batch_jobs_created", table_name="batch_jobs", postgresql_ops={"created_at": "DESC"}
    )
    op.drop_table("batch_jobs")
    op.drop_index("idx_auth_user_username", table_name="auth_user")
    op.drop_table("auth_user")
    op.drop_index("idx_api_usage_service", table_name="api_usage")
    op.drop_index(
        "idx_api_usage_recorded", table_name="api_usage", postgresql_ops={"recorded_at": "DESC"}
    )
    op.drop_table("api_usage")
    op.drop_index("idx_analysis_versions_type", table_name="analysis_versions")
    op.drop_index("idx_analysis_versions_symbol", table_name="analysis_versions")
    op.drop_index("idx_analysis_versions_expires", table_name="analysis_versions")
    op.drop_table("analysis_versions")
    op.drop_index("idx_ai_agent_analysis_symbol", table_name="ai_agent_analysis")
    op.drop_index("idx_ai_agent_analysis_signal", table_name="ai_agent_analysis")
    op.drop_index("idx_ai_agent_analysis_expires", table_name="ai_agent_analysis")
    op.drop_table("ai_agent_analysis")
    # ### end Alembic commands ###
