"""add_stock_info_cache_columns

Revision ID: 3f40fcf6b234
Revises: a76597402634
Create Date: 2025-12-29 18:17:09.149975+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f40fcf6b234"
down_revision: Union[str, None] = "a76597402634"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_agent_analysis",
        "agent_pending",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "symbols", sa.Column("fifty_two_week_low", sa.Numeric(precision=12, scale=4), nullable=True)
    )
    op.add_column(
        "symbols",
        sa.Column("fifty_two_week_high", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "symbols", sa.Column("previous_close", sa.Numeric(precision=12, scale=4), nullable=True)
    )
    op.add_column("symbols", sa.Column("avg_volume", sa.BigInteger(), nullable=True))
    op.add_column(
        "symbols", sa.Column("pe_ratio", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column(
        "symbols", sa.Column("stock_info_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("symbols", "stock_info_updated_at")
    op.drop_column("symbols", "pe_ratio")
    op.drop_column("symbols", "avg_volume")
    op.drop_column("symbols", "previous_close")
    op.drop_column("symbols", "fifty_two_week_high")
    op.drop_column("symbols", "fifty_two_week_low")
    op.alter_column(
        "ai_agent_analysis",
        "agent_pending",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
