"""drop_portfolio_cash_balance

Revision ID: 425459551ea8
Revises: 4416a7b94e51
Create Date: 2025-12-30 10:40:15.984746+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "425459551ea8"
down_revision: Union[str, None] = "4416a7b94e51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolios", "cash_balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios",
        sa.Column(
            "cash_balance", sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
