"""add_dip_entry_and_triggers_to_quant_precomputed

Revision ID: 4a35ce67ae76
Revises: a2546d638f37
Create Date: 2025-12-29 19:21:01.685830+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a35ce67ae76"
down_revision: Union[str, None] = "a2546d638f37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quant_precomputed",
        sa.Column("dip_entry_optimal_threshold", sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "quant_precomputed",
        sa.Column("dip_entry_optimal_price", sa.Numeric(precision=14, scale=4), nullable=True),
    )
    op.add_column(
        "quant_precomputed", sa.Column("dip_entry_is_buy_now", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "quant_precomputed",
        sa.Column("dip_entry_signal_strength", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "quant_precomputed", sa.Column("dip_entry_signal_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "quant_precomputed", sa.Column("dip_entry_recovery_days", sa.Integer(), nullable=True)
    )
    op.add_column(
        "quant_precomputed",
        sa.Column(
            "dip_entry_threshold_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "quant_precomputed",
        sa.Column("signal_triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quant_precomputed", "signal_triggers")
    op.drop_column("quant_precomputed", "dip_entry_threshold_analysis")
    op.drop_column("quant_precomputed", "dip_entry_recovery_days")
    op.drop_column("quant_precomputed", "dip_entry_signal_reason")
    op.drop_column("quant_precomputed", "dip_entry_signal_strength")
    op.drop_column("quant_precomputed", "dip_entry_is_buy_now")
    op.drop_column("quant_precomputed", "dip_entry_optimal_price")
    op.drop_column("quant_precomputed", "dip_entry_optimal_threshold")
    # ### end Alembic commands ###
