"""add_eva_columns_to_dip_state

Revision ID: 74c5e4daa063
Revises: 322fb07d2183
Create Date: 2025-12-29 14:16:19.554696+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74c5e4daa063"
down_revision: Union[str, None] = "322fb07d2183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dip_state",
        sa.Column("is_tail_event", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "dip_state",
        sa.Column("return_period_years", sa.Numeric(precision=6, scale=1), nullable=True),
    )
    op.add_column(
        "dip_state",
        sa.Column("regime_dip_percentile", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dip_state", "regime_dip_percentile")
    op.drop_column("dip_state", "return_period_years")
    op.drop_column("dip_state", "is_tail_event")
    # ### end Alembic commands ###
