"""add_domain_metrics_interest_expense_ratio

Revision ID: 19d3bbf89488
Revises: 3413a77cf8e2
Create Date: 2025-12-27 21:30:18.012841+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19d3bbf89488"
down_revision: Union[str, None] = "3413a77cf8e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_persona",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_persona",
        "display_order",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("idx_api_usage_recorded", table_name="api_usage")
    op.create_index(
        "idx_api_usage_recorded",
        "api_usage",
        ["recorded_at"],
        unique=False,
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.drop_index("idx_batch_jobs_created", table_name="batch_jobs")
    op.create_index(
        "idx_batch_jobs_created",
        "batch_jobs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_data_versions_updated", table_name="data_versions")
    op.create_index(
        "idx_data_versions_updated",
        "data_versions",
        ["updated_at"],
        unique=False,
        postgresql_ops={"updated_at": "DESC"},
    )
    op.drop_index("idx_dip_history_recorded", table_name="dip_history")
    op.create_index(
        "idx_dip_history_recorded",
        "dip_history",
        ["recorded_at"],
        unique=False,
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.drop_index("idx_dip_state_percentage", table_name="dip_state")
    op.create_index(
        "idx_dip_state_percentage",
        "dip_state",
        ["dip_percentage"],
        unique=False,
        postgresql_ops={"dip_percentage": "DESC"},
    )
    op.drop_index("idx_dip_state_updated", table_name="dip_state")
    op.create_index(
        "idx_dip_state_updated",
        "dip_state",
        ["last_updated"],
        unique=False,
        postgresql_ops={"last_updated": "DESC"},
    )
    op.drop_index("idx_dip_votes_created", table_name="dip_votes")
    op.create_index(
        "idx_dip_votes_created",
        "dip_votes",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_dipfinder_history_recorded", table_name="dipfinder_history")
    op.create_index(
        "idx_dipfinder_history_recorded",
        "dipfinder_history",
        ["recorded_at"],
        unique=False,
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.drop_index("idx_dipfinder_signals_date", table_name="dipfinder_signals")
    op.create_index(
        "idx_dipfinder_signals_date",
        "dipfinder_signals",
        ["as_of_date"],
        unique=False,
        postgresql_ops={"as_of_date": "DESC"},
    )
    op.drop_index("idx_dipfinder_signals_final", table_name="dipfinder_signals")
    op.create_index(
        "idx_dipfinder_signals_final",
        "dipfinder_signals",
        ["final_score"],
        unique=False,
        postgresql_ops={"final_score": "DESC"},
    )
    op.drop_index("idx_portfolio_analytics_created", table_name="portfolio_analytics")
    op.create_index(
        "idx_portfolio_analytics_created",
        "portfolio_analytics",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_portfolio_analytics_jobs_created", table_name="portfolio_analytics_jobs")
    op.create_index(
        "idx_portfolio_analytics_jobs_created",
        "portfolio_analytics_jobs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_portfolio_transactions_date", table_name="portfolio_transactions")
    op.create_index(
        "idx_portfolio_transactions_date",
        "portfolio_transactions",
        ["trade_date"],
        unique=False,
        postgresql_ops={"trade_date": "DESC"},
    )
    op.drop_index("idx_price_history_date", table_name="price_history")
    op.create_index(
        "idx_price_history_date",
        "price_history",
        ["date"],
        unique=False,
        postgresql_ops={"date": "DESC"},
    )
    op.alter_column(
        "settings_change_history",
        "reverted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("idx_settings_history_created", table_name="settings_change_history")
    op.create_index(
        "idx_settings_history_created",
        "settings_change_history",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.add_column(
        "stock_fundamentals", sa.Column("interest_income", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "stock_fundamentals", sa.Column("interest_expense", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "stock_fundamentals",
        sa.Column("expense_ratio", sa.Numeric(precision=10, scale=6), nullable=True),
    )
    op.drop_index("idx_suggestions_score", table_name="stock_suggestions")
    op.create_index(
        "idx_suggestions_score",
        "stock_suggestions",
        ["vote_score"],
        unique=False,
        postgresql_ops={"vote_score": "DESC"},
    )
    op.drop_index("idx_search_log_searched", table_name="symbol_search_log")
    op.create_index(
        "idx_search_log_searched",
        "symbol_search_log",
        ["searched_at"],
        unique=False,
        postgresql_ops={"searched_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_search_log_searched",
        table_name="symbol_search_log",
        postgresql_ops={"searched_at": "DESC"},
    )
    op.create_index(
        "idx_search_log_searched", "symbol_search_log", [sa.text("searched_at DESC")], unique=False
    )
    op.drop_index(
        "idx_suggestions_score",
        table_name="stock_suggestions",
        postgresql_ops={"vote_score": "DESC"},
    )
    op.create_index(
        "idx_suggestions_score", "stock_suggestions", [sa.text("vote_score DESC")], unique=False
    )
    op.drop_column("stock_fundamentals", "expense_ratio")
    op.drop_column("stock_fundamentals", "interest_expense")
    op.drop_column("stock_fundamentals", "interest_income")
    op.drop_index(
        "idx_settings_history_created",
        table_name="settings_change_history",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_settings_history_created",
        "settings_change_history",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "settings_change_history",
        "reverted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_index(
        "idx_price_history_date", table_name="price_history", postgresql_ops={"date": "DESC"}
    )
    op.create_index("idx_price_history_date", "price_history", [sa.text("date DESC")], unique=False)
    op.drop_index(
        "idx_portfolio_transactions_date",
        table_name="portfolio_transactions",
        postgresql_ops={"trade_date": "DESC"},
    )
    op.create_index(
        "idx_portfolio_transactions_date",
        "portfolio_transactions",
        [sa.text("trade_date DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_portfolio_analytics_jobs_created",
        table_name="portfolio_analytics_jobs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_portfolio_analytics_jobs_created",
        "portfolio_analytics_jobs",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_portfolio_analytics_created",
        table_name="portfolio_analytics",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_portfolio_analytics_created",
        "portfolio_analytics",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_dipfinder_signals_final",
        table_name="dipfinder_signals",
        postgresql_ops={"final_score": "DESC"},
    )
    op.create_index(
        "idx_dipfinder_signals_final",
        "dipfinder_signals",
        [sa.text("final_score DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_dipfinder_signals_date",
        table_name="dipfinder_signals",
        postgresql_ops={"as_of_date": "DESC"},
    )
    op.create_index(
        "idx_dipfinder_signals_date",
        "dipfinder_signals",
        [sa.text("as_of_date DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_dipfinder_history_recorded",
        table_name="dipfinder_history",
        postgresql_ops={"recorded_at": "DESC"},
    )
    op.create_index(
        "idx_dipfinder_history_recorded",
        "dipfinder_history",
        [sa.text("recorded_at DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_dip_votes_created", table_name="dip_votes", postgresql_ops={"created_at": "DESC"}
    )
    op.create_index(
        "idx_dip_votes_created", "dip_votes", [sa.text("created_at DESC")], unique=False
    )
    op.drop_index(
        "idx_dip_state_updated", table_name="dip_state", postgresql_ops={"last_updated": "DESC"}
    )
    op.create_index(
        "idx_dip_state_updated", "dip_state", [sa.text("last_updated DESC")], unique=False
    )
    op.drop_index(
        "idx_dip_state_percentage",
        table_name="dip_state",
        postgresql_ops={"dip_percentage": "DESC"},
    )
    op.create_index(
        "idx_dip_state_percentage", "dip_state", [sa.text("dip_percentage DESC")], unique=False
    )
    op.drop_index(
        "idx_dip_history_recorded", table_name="dip_history", postgresql_ops={"recorded_at": "DESC"}
    )
    op.create_index(
        "idx_dip_history_recorded", "dip_history", [sa.text("recorded_at DESC")], unique=False
    )
    op.drop_index(
        "idx_data_versions_updated",
        table_name="data_versions",
        postgresql_ops={"updated_at": "DESC"},
    )
    op.create_index(
        "idx_data_versions_updated", "data_versions", [sa.text("updated_at DESC")], unique=False
    )
    op.drop_index(
        "idx_batch_jobs_created", table_name="batch_jobs", postgresql_ops={"created_at": "DESC"}
    )
    op.create_index(
        "idx_batch_jobs_created", "batch_jobs", [sa.text("created_at DESC")], unique=False
    )
    op.drop_index(
        "idx_api_usage_recorded", table_name="api_usage", postgresql_ops={"recorded_at": "DESC"}
    )
    op.create_index(
        "idx_api_usage_recorded", "api_usage", [sa.text("recorded_at DESC")], unique=False
    )
    op.alter_column(
        "ai_persona",
        "display_order",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_persona",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
