"""add_max_profit_columns_to_quant_precomputed

Revision ID: ead0c5f7831d
Revises: 4a35ce67ae76
Create Date: 2025-12-29 22:04:43.426839+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ead0c5f7831d"
down_revision: Union[str, None] = "4a35ce67ae76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quant_precomputed",
        sa.Column(
            "dip_entry_max_profit_threshold", sa.Numeric(precision=10, scale=4), nullable=True
        ),
    )
    op.add_column(
        "quant_precomputed",
        sa.Column("dip_entry_max_profit_price", sa.Numeric(precision=14, scale=4), nullable=True),
    )
    op.add_column(
        "quant_precomputed",
        sa.Column(
            "dip_entry_max_profit_total_return", sa.Numeric(precision=10, scale=4), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quant_precomputed", "dip_entry_max_profit_total_return")
    op.drop_column("quant_precomputed", "dip_entry_max_profit_price")
    op.drop_column("quant_precomputed", "dip_entry_max_profit_threshold")
    # ### end Alembic commands ###
