"""add_agent_pending_column

Revision ID: a76597402634
Revises: 17324cd39318
Create Date: 2025-12-29 18:05:43.604379+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a76597402634"
down_revision: Union[str, None] = "17324cd39318"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_agent_analysis",
        sa.Column("agent_pending", sa.Boolean(), nullable=False, server_default=sa.text("FALSE")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_agent_analysis", "agent_pending")
    # ### end Alembic commands ###
