"""add_quant_precomputed_table

Revision ID: a2546d638f37
Revises: 3f40fcf6b234
Create Date: 2025-12-29 18:51:53.471049+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2546d638f37"
down_revision: Union[str, None] = "3f40fcf6b234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quant_precomputed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("backtest_signal_name", sa.String(length=100), nullable=True),
        sa.Column("backtest_n_trades", sa.Integer(), nullable=True),
        sa.Column("backtest_win_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("backtest_total_return_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column(
            "backtest_avg_return_per_trade", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        sa.Column("backtest_holding_days", sa.Integer(), nullable=True),
        sa.Column("backtest_buy_hold_return_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("backtest_edge_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("backtest_outperformed", sa.Boolean(), nullable=False),
        sa.Column("trade_entry_signal", sa.String(length=100), nullable=True),
        sa.Column("trade_entry_threshold", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trade_exit_signal", sa.String(length=100), nullable=True),
        sa.Column("trade_exit_threshold", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trade_n_trades", sa.Integer(), nullable=True),
        sa.Column("trade_win_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("trade_total_return_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trade_avg_return_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trade_sharpe_ratio", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("trade_buy_hold_return_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trade_spy_return_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trade_beats_both", sa.Boolean(), nullable=False),
        sa.Column("signal_combinations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dip_current_drawdown_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("dip_typical_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("dip_max_historical_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("dip_zscore", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("dip_type", sa.String(length=30), nullable=True),
        sa.Column("dip_action", sa.String(length=20), nullable=True),
        sa.Column("dip_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("dip_reasoning", sa.Text(), nullable=True),
        sa.Column("dip_recovery_probability", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("current_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_start", sa.Date(), nullable=True),
        sa.Column("data_end", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quant_precomputed")),
        sa.UniqueConstraint("symbol", name=op.f("uq_quant_precomputed_symbol")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quant_precomputed")
    # ### end Alembic commands ###
