"""add_calendar_events_tables

Revision ID: 25f8162273f8
Revises: 6cec0b053d87
Create Date: 2026-01-03 22:54:25.560257+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25f8162273f8"
down_revision: Union[str, None] = "6cec0b053d87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_earnings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=True),
        sa.Column("earnings_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("earnings_time", sa.String(length=20), nullable=True),
        sa.Column("eps_estimate", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("eps_actual", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("surprise_percent", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_earnings")),
        sa.UniqueConstraint("symbol", "earnings_date", name="uq_calendar_earnings_symbol_date"),
    )
    op.create_table(
        "calendar_economic_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_name", sa.String(length=300), nullable=False),
        sa.Column("event_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("estimate", sa.String(length=100), nullable=True),
        sa.Column("actual", sa.String(length=100), nullable=True),
        sa.Column("prior", sa.String(length=100), nullable=True),
        sa.Column("importance", sa.String(length=20), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_economic_events")),
        sa.UniqueConstraint("event_name", "event_date", name="uq_calendar_econ_event_date"),
    )
    op.create_table(
        "calendar_ipos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("company_name", sa.String(length=300), nullable=False),
        sa.Column("ipo_date", sa.Date(), nullable=False),
        sa.Column("price_range_low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_range_high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("offer_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("shares_offered", sa.BigInteger(), nullable=True),
        sa.Column("deal_size", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("exchange", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_ipos")),
        sa.UniqueConstraint("company_name", "ipo_date", name="uq_calendar_ipos_company_date"),
    )
    op.create_table(
        "calendar_splits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=True),
        sa.Column("split_date", sa.Date(), nullable=False),
        sa.Column("split_ratio", sa.String(length=20), nullable=False),
        sa.Column("split_from", sa.Integer(), nullable=True),
        sa.Column("split_to", sa.Integer(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_splits")),
        sa.UniqueConstraint("symbol", "split_date", name="uq_calendar_splits_symbol_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_splits")
    op.drop_table("calendar_ipos")
    op.drop_table("calendar_economic_events")
    op.drop_table("calendar_earnings")
    # ### end Alembic commands ###
