"""add_multi_tenant_security_fields

Revision ID: 2ac90fc3aee7
Revises: 25f8162273f8
Create Date: 2026-01-04 19:13:13.417971+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ac90fc3aee7"
down_revision: Union[str, None] = "25f8162273f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Auth user columns - add with defaults to handle existing data
    op.add_column("auth_user", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "auth_user",
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("auth_user", sa.Column("avatar_url", sa.Text(), nullable=True))
    op.add_column(
        "auth_user",
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "auth_user",
        sa.Column("auth_provider", sa.String(length=20), server_default="local", nullable=False),
    )
    op.add_column("auth_user", sa.Column("provider_id", sa.String(length=255), nullable=True))
    op.add_column(
        "auth_user", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "auth_user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_unique_constraint(op.f("uq_auth_user_email"), "auth_user", ["email"])
    
    # Portfolio columns - add with defaults to handle existing data
    op.add_column(
        "portfolios",
        sa.Column("visibility", sa.String(length=20), server_default="private", nullable=False),
    )
    op.add_column("portfolios", sa.Column("share_token", sa.String(length=64), nullable=True))
    op.add_column("portfolios", sa.Column("shared_at", sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f("uq_portfolios_share_token"), "portfolios", ["share_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_portfolios_share_token"), "portfolios", type_="unique")
    op.drop_column("portfolios", "shared_at")
    op.drop_column("portfolios", "share_token")
    op.drop_column("portfolios", "visibility")
    op.drop_constraint(op.f("uq_auth_user_email"), "auth_user", type_="unique")
    op.alter_column(
        "auth_user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("auth_user", "last_login_at")
    op.drop_column("auth_user", "provider_id")
    op.drop_column("auth_user", "auth_provider")
    op.drop_column("auth_user", "preferences")
    op.drop_column("auth_user", "avatar_url")
    op.drop_column("auth_user", "email_verified")
    op.drop_column("auth_user", "email")
    # ### end Alembic commands ###
