"""add_strategy_comparison_jsonb

Revision ID: a221a942d697
Revises: b7ff34314dc9
Create Date: 2026-01-05 20:44:32.660791+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a221a942d697"
down_revision: Union[str, None] = "b7ff34314dc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy_signals",
        sa.Column("strategy_comparison", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_signals", "strategy_comparison")
    # ### end Alembic commands ###
