"""add_dip_entry_signal_triggers

Revision ID: b7ff34314dc9
Revises: 317c4501d9f9
Create Date: 2026-01-05 13:23:12.876621+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7ff34314dc9"
down_revision: Union[str, None] = "317c4501d9f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quant_precomputed",
        sa.Column(
            "dip_entry_signal_triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quant_precomputed", "dip_entry_signal_triggers")
    # ### end Alembic commands ###
