"""add_market_sectors_and_industries

Revision ID: 6cec0b053d87
Revises: 8628a993c359
Create Date: 2026-01-03 22:42:51.493833+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6cec0b053d87"
down_revision: Union[str, None] = "8628a993c359"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_sectors",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("overview", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("top_companies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("top_etfs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("top_mutual_funds", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("research_reports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_market_sectors")),
    )
    op.create_table(
        "market_industries",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("sector_key", sa.String(length=100), nullable=False),
        sa.Column("sector_name", sa.String(length=200), nullable=False),
        sa.Column("overview", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("top_companies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "top_performing_companies", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("top_growth_companies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("research_reports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sector_key"],
            ["market_sectors.key"],
            name=op.f("fk_market_industries_sector_key_market_sectors"),
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_market_industries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_industries")
    op.drop_table("market_sectors")
    # ### end Alembic commands ###
